version: "3.8"

services:

  postgresql:
    container_name: rtrw_serpong_postgres
    image: postgis/postgis:latest
    # env_file: postgres/docker.env
    env_file: docker.env
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    # networks:
    #   - rtrwserpong_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  django:
    # restart: always
    image: rtrw_serpong_django
    container_name: rtrw_serpong_django
    hostname: rtrw_serpong_django
    build:
      context: .
      dockerfile: Dockerfile
    env_file: docker.env
    # networks:
    #   - rtrwserpong_net
    ports:
      - "28000:8000"
    volumes:
      - ./rtrw_serpong:/code/rtrw_serpong/
      - django_static_volume:/code/rtrw_serpong/static
    # volumes:
    #   - ./rtrw_serpong:/code/
      # - django_static_volume:/code/static
    #   - django_media_volume:/code/media
    # depends_on:
    #   - redis
    # entrypoint: code/entrypoint.sh
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nginx:
    container_name: rtrw_serpong_nginx
    image: nginx:alpine
    restart: always
    env_file: docker.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - django_static_volume:/usr/share/nginx/html/
    ports:
      - 20080:80
  #   # networks:
  #   #   - nginx_net

# networks:
#   rtrwserpong_net:
#     external: true

volumes:
  django_static_volume:
  django_media_volume:
  pgdata: