version: "3.8"

services:

  django:
    # restart: always
    image: rtrw_serpong_django
    container_name: rtrw_serpong_django
    hostname: rtrw_serpong_django
    build:
      context: .
      dockerfile: Dockerfile
    env_file: docker.env
    # networks:
    #   - rtrwserpong_net
    ports:
      - "28000:8000"
    volumes:
      - ./rtrw_serpong:/code/rtrw_serpong/
      - django_static_volume:/code/rtrw_serpong/static
    # volumes:
    #   - ./rtrw_serpong:/code/
      # - django_static_volume:/code/static
    #   - django_media_volume:/code/media
    # depends_on:
    #   - redis
    # entrypoint: code/entrypoint.sh
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

# networks:
#   rtrwserpong_net:
#     external: true

volumes:
  django_static_volume:
  django_media_volume:
  pgdata: