# Generated by Django 3.2.3 on 2021-05-29 08:05

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidangTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('deskripsi', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('geom', djgeojson.fields.PolygonField()),
            ],
            options={
                'verbose_name': 'Bidang Tanah',
                'verbose_name_plural': 'Bidang Tanah',
            },
        ),
    ]
