# Generated by Django 3.2.4 on 2021-06-13 05:32

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('deskripsi', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('geom', djgeojson.fields.PolygonField()),
            ],
            options={
                'verbose_name': 'Bidang Tanah',
                'verbose_name_plural': 'Bidang Tanah',
            },
        ),
        migrations.CreateModel(
            name='Bangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('alamat', models.CharField(max_length=255)),
                ('geom', djgeojson.fields.PolygonField(null=True)),
                ('bidang_tanah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bidangtanah')),
                ('fungsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.fungsibangunan')),
            ],
            options={
                'verbose_name': 'Bangunan',
                'verbose_name_plural': 'Bangunan',
            },
        ),
    ]
