# Generated by Django 3.2.4 on 2021-06-16 18:45

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('kependudukan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('deskripsi', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('geom', djgeojson.fields.PolygonField()),
                ('induk', models.ForeignKey(blank=True, help_text='Bidang tanah induk yang mencakupi', null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bidangtanah')),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kependudukan.biodata')),
                ('tipe_bidang_tanah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.tipebidangtanah')),
            ],
            options={
                'verbose_name': 'Bidang Tanah',
                'verbose_name_plural': 'Bidang Tanah',
            },
        ),
        migrations.CreateModel(
            name='Bangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('alamat', models.CharField(max_length=255)),
                ('geom', djgeojson.fields.PolygonField(null=True)),
                ('bidang_tanah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bidangtanah')),
                ('fungsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.fungsibangunan')),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kependudukan.biodata')),
            ],
            options={
                'verbose_name': 'Bangunan',
                'verbose_name_plural': 'Bangunan',
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nomor', models.CharField(blank=True, max_length=3, null=True)),
                ('disewakan', models.BooleanField(default=False)),
                ('bangunan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bangunan')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
                'unique_together': {('bangunan', 'nomor')},
            },
        ),
    ]
