# Generated by Django 3.2.4 on 2021-06-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0001_initial'),
        ('tata_ruang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kependudukan.biodata'),
        ),
        migrations.AddField(
            model_name='bidangtanah',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kependudukan.biodata'),
        ),
    ]
