# Generated by Django 3.2.3 on 2021-05-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata_ruang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('alamat', models.CharField(max_length=255)),
                ('bidang_tanah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bidangtanah')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
