# Generated by Django 3.2.3 on 2021-05-29 10:34

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tata_ruang', '0002_bangunan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangunan',
            options={'verbose_name': 'Bangunan', 'verbose_name_plural': 'Bangunan'},
        ),
        migrations.AddField(
            model_name='bangunan',
            name='geom',
            field=djgeojson.fields.PolygonField(null=True),
        ),
    ]
