# Generated by Django 3.2.3 on 2021-05-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_fungsibangunan'),
        ('tata_ruang', '0003_auto_20210529_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan',
            name='fungsi',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='master.fungsibangunan'),
            preserve_default=False,
        ),
    ]
