# Generated by Django 3.2.4 on 2021-06-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata_ruang', '0005_alter_bangunan_bidang_tanah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunan',
            name='bidang_tanah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bidangtanah'),
        ),
    ]
