# Generated by Django 3.2.4 on 2021-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agama',
                'verbose_name_plural': 'Agama',
            },
        ),
        migrations.CreateModel(
            name='FungsiBangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fungsi Bangunan',
                'verbose_name_plural': 'Fungsi Bangunan',
            },
        ),
        migrations.CreateModel(
            name='Gelar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gelar',
                'verbose_name_plural': 'Gelar',
            },
        ),
        migrations.CreateModel(
            name='GolonganDarah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Golongan Darah',
                'verbose_name_plural': 'Golongan Darah',
            },
        ),
        migrations.CreateModel(
            name='HubunganKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hubungan Keluarga',
                'verbose_name_plural': 'Hubungan Keluarga',
            },
        ),
        migrations.CreateModel(
            name='JenisKelamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Jenis Kelamin',
                'verbose_name_plural': 'Jenis Kelamin',
            },
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pekerjaan',
                'verbose_name_plural': 'Pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pendidikan',
                'verbose_name_plural': 'Pendidikan',
            },
        ),
        migrations.CreateModel(
            name='PenyandangCacat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Penyandang Cacat',
                'verbose_name_plural': 'Penyandang Cacat',
            },
        ),
        migrations.CreateModel(
            name='StatusKawin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status Kawin',
                'verbose_name_plural': 'Status Kawin',
            },
        ),
        migrations.CreateModel(
            name='StatusPenguasaanTempatTinggal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Status Penguasaan Tempat Tinggal',
                'verbose_name_plural': 'Status Penguasaan Tempat Tinggal',
            },
        ),
        migrations.CreateModel(
            name='TipeBidangTanah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipe Bidang Tanah',
                'verbose_name_plural': 'Tipe Bidang Tanah',
            },
        ),
    ]
