# Generated by Django 3.2.3 on 2021-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agama',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='agama',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='agama',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='agama',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='gelar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='gelar',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='gelar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='gelar',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='golongandarah',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='golongandarah',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='golongandarah',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='golongandarah',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='hubungankeluarga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='hubungankeluarga',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='hubungankeluarga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='hubungankeluarga',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='jeniskelamin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='jeniskelamin',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='jeniskelamin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='jeniskelamin',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='penyandangcacat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='penyandangcacat',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='penyandangcacat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='penyandangcacat',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='statuskawin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='statuskawin',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='statuskawin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='statuskawin',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
    ]
