# Generated by Django 3.2.3 on 2021-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210529_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungsiBangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh')),
                ('nama', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fungsi Bangunan',
                'verbose_name_plural': 'Fungsi Bangunan',
            },
        ),
    ]
