version: "3"
services:
  postgresql:
    container_name: rtrw_serpong_postgres
    image: postgis/postgis:latest
    env_file: postgres/docker.env
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    networks:
      - rtrwserpong_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nginx:
    container_name: rtrw_serpong_nginx
    image: nginx:alpine
    build: 
      context: ..
      dockerfile: docker/nginx/Dockerfile
    restart: always
    env_file: nginx/docker.env
    # volumes:
    #   - nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 20080:80
    networks:
      - nginx_net

networks:
  nginx_net:

volumes: 
  pgdata:
