version: "3.7"
services:
  postgresql:
    container_name: postgres
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file: .env
    networks:
      - django-net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
    networks:
      - nginx_net

networks:
  django-net:
