version: "3"

services:

  postgresql:
    container_name: rtrw_serpong_postgres
    image: postgis/postgis:latest
    env_file: postgres/docker.env
    ports:
      - 25432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    # networks:
    #   - rtrwserpong_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  django:
    restart: always
    image: rtrw_serpong_django
    container_name: rtrw_serpong_django
    hostname: rtrw_serpong_django
    build:
      context: ..
      dockerfile: docker/django/Dockerfile
    env_file: django/docker.env
    # networks:
    #   - rtrwserpong_net
    ports:
      - "28000:8000"
    # volumes:
    #   - ./rtrw_serpong:/code/
      # - django_static_volume:/code/static
    #   - django_media_volume:/code/media
    # depends_on:
    #   - redis
    # entrypoint: code/entrypoint.sh
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nginx:
    container_name: rtrw_serpong_nginx
    image: nginx:alpine
    build: 
      context: ..
      dockerfile: docker/nginx/Dockerfile
    restart: always
    env_file: nginx/docker.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 20080:80
    # networks:
    #   - nginx_net

# networks:
#   rtrwserpong_net:
#     external: true

volumes:
  django_static_volume:
  django_media_volume:
  pgdata: