version: "3.7"

services:

  django:
    restart: always
    image: django
    container_name: django
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: .env
    networks:
      - rtrwserpong_net
    ports:
      - 8000:8000
    volumes:
      # - ./rtrw_serpong:/code/
      - django_static_volume:/code/static
      - django_media_volume:/code/media
    # depends_on:
    #   - redis
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

networks:
  rtrwserpong_net:
    external: true

volumes:
  django_static_volume:
  django_media_volume:
