# Generated by Django 3.2.3 on 2021-05-29 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('no_kk', models.CharField(max_length=16, unique=True, verbose_name='No KK')),
                ('nama_kepala', models.CharField(max_length=180)),
                ('alamat', models.CharField(max_length=360)),
            ],
            options={
                'verbose_name': 'Keluarga',
                'verbose_name_plural': 'Keluarga',
            },
        ),
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('no_paspor', models.CharField(max_length=90, null=True)),
                ('nama_lengkap', models.CharField(max_length=180)),
                ('tempat_lahir', models.CharField(max_length=180)),
                ('tanggal_lahir', models.DateField()),
                ('no_akta_lahir', models.CharField(max_length=120, null=True)),
                ('no_akta_kawin', models.CharField(max_length=120, null=True)),
                ('tanggal_kawin', models.DateField()),
                ('no_akta_cerai', models.CharField(max_length=120, null=True)),
                ('tanggal_cerai', models.DateField()),
                ('nik_ibu', models.CharField(max_length=16)),
                ('nama_lengkap_ibu', models.CharField(max_length=180)),
                ('nik_ayah', models.CharField(max_length=16)),
                ('nama_lengkap_ayah', models.CharField(max_length=180)),
                ('nama_ketua_rt', models.CharField(blank=True, max_length=180, null=True)),
                ('nama_ketua_rw', models.CharField(blank=True, max_length=180, null=True)),
                ('no_kk', models.CharField(blank=True, max_length=16, null=True, verbose_name='No KK')),
                ('agama', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.agama')),
                ('golongan_darah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.golongandarah')),
                ('jenis_kelamin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.jeniskelamin')),
                ('jenis_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.pekerjaan')),
                ('keluarga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kependudukan.keluarga')),
                ('pendidikan_akhir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.pendidikan')),
                ('stat_hubungan_keluarga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.hubungankeluarga')),
                ('status_kawin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.statuskawin')),
            ],
            options={
                'verbose_name': 'Biodata',
                'verbose_name_plural': 'Biodata',
            },
        ),
    ]
