# Generated by Django 3.2.3 on 2021-05-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='no_kk',
        ),
        migrations.AlterField(
            model_name='biodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='keluarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kependudukan.keluarga', verbose_name='No KK'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='nama_ketua_rt',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Nama ketua RT'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='nama_ketua_rw',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Nama ketua RW'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='nik',
            field=models.CharField(max_length=16, unique=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='nik_ayah',
            field=models.CharField(max_length=16, verbose_name='NIK ayah'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='nik_ibu',
            field=models.CharField(max_length=16, verbose_name='NIK ibu'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
        migrations.AlterField(
            model_name='keluarga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Data Dibuat'),
        ),
        migrations.AlterField(
            model_name='keluarga',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='keluarga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tanggal Data Diperbarui'),
        ),
        migrations.AlterField(
            model_name='keluarga',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Diperbarui Oleh'),
        ),
    ]
