# Generated by Django 3.2.4 on 2021-06-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('tata_ruang', '0001_initial'),
        ('kependudukan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domisili',
            name='indekos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.ruangan'),
        ),
        migrations.AddField(
            model_name='domisili',
            name='rumah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tata_ruang.bangunan'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='agama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.agama'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='golongan_darah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.golongandarah'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='jenis_kelamin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.jeniskelamin'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='jenis_pekerjaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.pekerjaan'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='keluarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kependudukan.keluarga', verbose_name='No KK'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='pendidikan_akhir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.pendidikan'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='stat_hubungan_keluarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.hubungankeluarga'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='status_kawin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.statuskawin'),
        ),
    ]
