# Generated by Django 3.2.3 on 2021-06-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0002_auto_20210529_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='no_akta_cerai',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='no_akta_kawin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='no_akta_lahir',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='no_paspor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='tanggal_cerai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='tanggal_kawin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
